# Generated by Django 3.1.1 on 2020-11-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201105_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email of Seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name of Seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name of Seller'),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name of Seller'),
        ),
    ]
