# Generated by Django 3.1.1 on 2020-09-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_description', models.CharField(blank=True, max_length=255, null=True)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_location', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_address', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_email', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.producttype')),
            ],
            options={
                'verbose_name': ('Product',),
                'verbose_name_plural': 'Products',
            },
        ),
    ]
