# Generated by Django 3.1.1 on 2020-11-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
