# Generated by Django 3.1.1 on 2020-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/product_images/'),
        ),
    ]
